doj:
    port:
        gateway-service: 8080
        user-service: 8081
        sandbox-service: 8082
        problem-service: 8083
        submission-service: 8084

    resource:
        location: "/Users/qzj/Desktop/Development/D-OnlineJudge/static/files/"
        request: "/static/"

        code-path: "/Users/qzj/Desktop/Development/D-OnlineJudge/static/codes/"
        problem-code-path: "/Users/qzj/Desktop/Development/D-OnlineJudge/static/problem-codes/"