server:
    port: ${doj.port.gateway-service}

doj:
    auth:
        excludePaths:
            - /
            - /static/**
            - /user/login
            - /user/register
            - /user/refresh