global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'doj-services'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          service: "gateway-service"
      - targets: ["host.docker.internal:8081"]
        labels:
          service: "user-service"
      - targets: ["host.docker.internal:8082"]
        labels:
          service: "sandbox-service"
      - targets: ["host.docker.internal:8083"]
        labels:
          service: "problem-service"
      - targets: ["host.docker.internal:8084"]
        labels:
          service: "submission-service"