FROM python:3.10-slim

# 安装必要工具用于统计资源
RUN apt-get update && apt-get install -y time && apt-get clean

WORKDIR /app
COPY . /app

# 使用 /usr/bin/time 获取内存使用和时间
CMD ["/bin/bash", "-c", "/usr/bin/time -v timeout 5s python3 Main.py"]