server:
    port: ${doj.port.submission-service}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

doj:
    db:
        host: ${DOJ_DB_HOST:127.0.0.1}
        name: doj_submission
        user: ${DOJ_DB_USER:root}
        pwd: ${DOJ_DB_PWD:123}
    mq:
        host: ${DOJ_MQ_HOST:127.0.0.1}
    swagger:
        title: 沙箱接口文档
        scan: com.decade.doj.submission.controller