server:
    port: ${doj.port.sandbox-service}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

doj:
    redis:
        host: ${DOJ_REDIS_HOST:127.0.0.1}
    swagger:
        title: 沙箱接口文档
        scan: com.decade.doj.sandbox.controller