server:
    port: ${doj.port.sandbox-service}
doj:
    db:
        host: 127.0.0.1
        name: doj_user
        user: root
        pwd: 123
    swagger:
        title: 沙箱接口文档
        scan: com.decade.doj.sandbox.controller